name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Workspace Build
      run: make build

    # the ros2/examples repo has stderr output on most tests :)
    # - name: Workspace Test
    #   run: make test

    - name: Final Image
      run: make final

