name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Workspace Build
      run: make update-submodules

    - name: Workspace Build
      run: make build

    - name: Final Image
      run: make final
